# ===========================================================
# vowelTriangle.r
# Rolando Coto-Solano. Victoria University of Wellington
# rolando.coto@vuw.ac.nz
# Last update: 20181202
#
# This code takes a file generated by the getPhonetics.praat 
# script (or the getDurationPitchFormants.praat of Mietta
# Lennes) and makess a vowel triangle using the phonR 
# package. These instructions are from the tutorial at:
# http://drammock.github.io/phonR/
# ===========================================================

# Load the necessary libraries
library(phonR)
library(ggplot2)

# Read the file
inputSounds = read.table("C:\\Users\\Bender\\Desktop\\workshop\\resultsfile.txt", sep="\t", dec=",", row.names=NULL, header=TRUE)

# Set the "undefined" pitch tracks to null
inputSounds[inputSounds=="--undefined--"] = ""

# Filter the inputSounds dataframe so that it has only vowels.
# (This needs to be modified to the vowels in your dataframe)
inputSounds = subset(inputSounds, TextGridLabel == "AH1" | TextGridLabel == "AH0" | TextGridLabel == "IY1")

# Draw all the tokens and the centroid of each vowel
with(inputSoundsutSounds, 
     plotVowels(F1_midpoint, F2_midpoint, TextGridLabel, plot.tokens = TRUE, 
                                   plot.means = TRUE, pch.means = TextGridLabel, pch.tokens=TextGridLabel, 
                                   cex.means = 2, var.col.by = TextGridLabel, family = "Charis SIL", pretty = TRUE))

# Draw the centroid of each vowel and an ellipse of ±1 standard deviation
with(inputSounds, plotVowels(F1_midpoint, F2_midpoint, TextGridLabel, group = TextGridLabel, plot.tokens = FALSE, plot.means = TRUE, 
                      pch.means = TextGridLabel, cex.means = 2, var.col.by = TextGridLabel, ellipse.fill = TRUE, pretty = TRUE))